import Erdos81.TerminalAssignment
import Erdos81.TrianglePacking
import Mathlib.Tactic

/-!
# Hosted outside-edge triangles

Accepted outside edges become triangles by adjoining their assigned root
vertex.  This file constructs those triangles as certified three-cliques and
records their exact cardinality.
-/

namespace Erdos81
namespace HostedTriangles

open MixedModel ExternalInputs EdgeColoring RootedGraph RootedPEO
  TerminalAssignment

attribute [-instance] MixedModel.resourceFintype

variable {V Color : Type*} [Fintype V] [DecidableEq V]
  [Fintype Color] [DecidableEq Color]

/-- The vertices of the triangle generated by a retained outside edge. -/
noncomputable def vertices {G : SimpleGraph V} [DecidableRel G.Adj]
    {P : Finset V} (O : RootedPEO.Order G P)
    (C : ProperEdgeColoring (outsideGraph G P) Color)
    (S : Finset Color) (assign : ↑S ≃ ↑P)
    (e : ↑(retainedAssignedEdges O C S assign)) : Finset V :=
  insert (assignedHost C S assign e.1) e.1.1.1.toFinset

theorem host_mem_root {G : SimpleGraph V} [DecidableRel G.Adj]
    {P : Finset V} (O : RootedPEO.Order G P)
    (C : ProperEdgeColoring (outsideGraph G P) Color)
    (S : Finset Color) (assign : ↑S ≃ ↑P)
    (e : ↑(retainedAssignedEdges O C S assign)) :
    assignedHost C S assign e.1 ∈ P :=
  (assign (assignedColor C S e.1)).property

theorem host_admits {G : SimpleGraph V} [DecidableRel G.Adj]
    {P : Finset V} (O : RootedPEO.Order G P)
    (C : ProperEdgeColoring (outsideGraph G P) Color)
    (S : Finset Color) (assign : ↑S ≃ ↑P)
    (e : ↑(retainedAssignedEdges O C S assign)) :
    ∀ y ∈ e.1.1.1.toFinset, G.Adj (assignedHost C S assign e.1) y := by
  apply (not_mem_invalidHostsForResource_iff O e.1.1
    (host_mem_root O C S assign e)).mp
  have he := e.2
  simpa [retainedAssignedEdges] using (Finset.mem_filter.mp he).2

/-- The endpoints of a graph resource form a two-vertex clique. -/
theorem resource_toFinset_isClique {H : SimpleGraph V}
    (e : Resource H) : H.IsClique (e.1.toFinset : Set V) := by
  classical
  revert e
  rintro ⟨edge, hedge⟩
  refine Sym2.inductionOn edge ?_ hedge
  intro u v huv x hx y hy hxy
  have huvAdj : H.Adj u v := H.mem_edgeSet.mp huv
  have hx' : x = u ∨ x = v := by
    rw [← Sym2.mem_iff]
    exact Sym2.mem_toFinset.mp hx
  have hy' : y = u ∨ y = v := by
    rw [← Sym2.mem_iff]
    exact Sym2.mem_toFinset.mp hy
  rcases hx' with rfl | rfl <;> rcases hy' with rfl | rfl
  · exact (hxy rfl).elim
  · exact huvAdj
  · exact huvAdj.symm
  · exact (hxy rfl).elim

theorem host_not_mem_edge {G : SimpleGraph V} [DecidableRel G.Adj]
    {P : Finset V} (O : RootedPEO.Order G P)
    (C : ProperEdgeColoring (outsideGraph G P) Color)
    (S : Finset Color) (assign : ↑S ≃ ↑P)
    (e : ↑(retainedAssignedEdges O C S assign)) :
    assignedHost C S assign e.1 ∉ e.1.1.1.toFinset := by
  intro hhost
  exact (mem_outsideVertices.mp
    (resource_endpoint_mem_outside O e.1.1 hhost))
    (host_mem_root O C S assign e)

theorem vertices_card {G : SimpleGraph V} [DecidableRel G.Adj]
    {P : Finset V} (O : RootedPEO.Order G P)
    (C : ProperEdgeColoring (outsideGraph G P) Color)
    (S : Finset Color) (assign : ↑S ≃ ↑P)
    (e : ↑(retainedAssignedEdges O C S assign)) :
    (vertices O C S assign e).card = 3 := by
  rw [vertices, Finset.card_insert_of_notMem
    (host_not_mem_edge O C S assign e), resource_toFinset_card]

theorem vertices_isClique {G : SimpleGraph V} [DecidableRel G.Adj]
    {P : Finset V} (O : RootedPEO.Order G P)
    (C : ProperEdgeColoring (outsideGraph G P) Color)
    (S : Finset Color) (assign : ↑S ≃ ↑P)
    (e : ↑(retainedAssignedEdges O C S assign)) :
    G.IsClique (vertices O C S assign e : Set V) := by
  classical
  intro x hx y hy hxy
  simp only [vertices, Finset.coe_insert, Set.mem_insert_iff] at hx hy
  rcases hx with hx | hx
  · subst x
    rcases hy with hy | hy
    · exact (hxy hy.symm).elim
    · exact host_admits O C S assign e y hy
  · rcases hy with hy | hy
    · subst y
      exact (host_admits O C S assign e x hx).symm
    · exact ((outsideGraph_adj G P x y).mp
        (resource_toFinset_isClique e.1.1 hx hy hxy)).1

/-- A hosted outside-edge triangle contains exactly its host in the root. -/
theorem vertices_inter_root {G : SimpleGraph V} [DecidableRel G.Adj]
    {P : Finset V} (O : RootedPEO.Order G P)
    (C : ProperEdgeColoring (outsideGraph G P) Color)
    (S : Finset Color) (assign : ↑S ≃ ↑P)
    (e : ↑(retainedAssignedEdges O C S assign)) :
    vertices O C S assign e ∩ P = {assignedHost C S assign e.1} := by
  classical
  apply Finset.ext
  intro x
  constructor
  · intro hx
    have hx' := Finset.mem_inter.mp hx
    simp only [vertices, Finset.mem_insert] at hx'
    rcases hx'.1 with hxHost | hxEdge
    · simpa [hxHost]
    · exact ((mem_outsideVertices.mp
        (resource_endpoint_mem_outside O e.1.1 hxEdge)) hx'.2).elim
  · intro hx
    have hxHost : x = assignedHost C S assign e.1 := by simpa using hx
    subst x
    exact Finset.mem_inter.mpr
      ⟨by simp [vertices], host_mem_root O C S assign e⟩

/-- The certified triangle associated with a retained outside edge. -/
noncomputable def triangle {G : SimpleGraph V} [DecidableRel G.Adj]
    {P : Finset V} (O : RootedPEO.Order G P)
    (C : ProperEdgeColoring (outsideGraph G P) Color)
    (S : Finset Color) (assign : ↑S ≃ ↑P)
    (e : ↑(retainedAssignedEdges O C S assign)) : CliqueOfOrder G 3 :=
  ⟨vertices O C S assign e,
    vertices_card O C S assign e, vertices_isClique O C S assign e⟩

theorem triangle_injective {G : SimpleGraph V} [DecidableRel G.Adj]
    {P : Finset V} (O : RootedPEO.Order G P)
    (C : ProperEdgeColoring (outsideGraph G P) Color)
    (S : Finset Color) (assign : ↑S ≃ ↑P) :
    Function.Injective (triangle O C S assign) := by
  intro e f hef
  apply Subtype.ext
  apply Subtype.ext
  apply Subtype.ext
  apply Sym2.ext
  intro x
  rw [← Sym2.mem_toFinset, ← Sym2.mem_toFinset]
  have hvertices := congrArg Subtype.val hef
  change vertices O C S assign e = vertices O C S assign f at hvertices
  have houtside : x ∈ outsideVertices P →
      (x ∈ vertices O C S assign e ↔
        x ∈ vertices O C S assign f) := fun _ ↦ by rw [hvertices]
  constructor
  · intro hx
    have hxOut := resource_endpoint_mem_outside O e.1.1 hx
    have hxTri : x ∈ vertices O C S assign e := by
      simp [vertices, hx]
    have hxTriF := (houtside hxOut).mp hxTri
    have hxNeHost : x ≠ assignedHost C S assign f.1 := by
      intro h
      exact (mem_outsideVertices.mp hxOut)
        (h.symm ▸ host_mem_root O C S assign f)
    simpa [vertices, hxNeHost] using hxTriF
  · intro hx
    have hxOut := resource_endpoint_mem_outside O f.1.1 hx
    have hxTri : x ∈ vertices O C S assign f := by
      simp [vertices, hx]
    have hxTriE := (houtside hxOut).mpr hxTri
    have hxNeHost : x ≠ assignedHost C S assign e.1 := by
      intro h
      exact (mem_outsideVertices.mp hxOut)
        (h.symm ▸ host_mem_root O C S assign e)
    simpa [vertices, hxNeHost] using hxTriE

/-- Two hosted triangles sharing a graph edge come from the same retained
outside edge. -/
theorem eq_of_shared_edge {G : SimpleGraph V} [DecidableRel G.Adj]
    {P : Finset V} (O : RootedPEO.Order G P)
    (C : ProperEdgeColoring (outsideGraph G P) Color)
    (S : Finset Color) (assign : ↑S ≃ ↑P)
    (e f : ↑(retainedAssignedEdges O C S assign))
    (r : Resource G)
    (her : Uses (Sum.inl (triangle O C S assign e)) r)
    (hfr : Uses (Sum.inl (triangle O C S assign f)) r) : e = f := by
  classical
  change r.1.toFinset ⊆ vertices O C S assign e at her
  change r.1.toFinset ⊆ vertices O C S assign f at hfr
  by_cases hroot : ∃ x ∈ r.1.toFinset, x ∈ P
  · obtain ⟨x, hxR, hxP⟩ := hroot
    have hxE := her hxR
    have hxF := hfr hxR
    simp only [vertices, Finset.mem_insert] at hxE hxF
    have hxHostE : x = assignedHost C S assign e.1 := by
      rcases hxE with hxHost | hxOutside
      · exact hxHost
      · exact ((mem_outsideVertices.mp
          (resource_endpoint_mem_outside O e.1.1 hxOutside)) hxP).elim
    have hxHostF : x = assignedHost C S assign f.1 := by
      rcases hxF with hxHost | hxOutside
      · exact hxHost
      · exact ((mem_outsideVertices.mp
          (resource_endpoint_mem_outside O f.1.1 hxOutside)) hxP).elim
    have hhost : assignedHost C S assign e.1 =
        assignedHost C S assign f.1 := hxHostE.symm.trans hxHostF
    obtain ⟨y, hyR, hyx⟩ := Finset.exists_mem_ne
      (show 1 < r.1.toFinset.card from by
        let rf : ↑G.edgeFinset := ⟨r.1, G.mem_edgeFinset.mpr r.2⟩
        have hcard := G.card_toFinset_mem_edgeFinset rf
        change r.1.toFinset.card = 2 at hcard
        omega) x
    have hyE := her hyR
    have hyF := hfr hyR
    simp only [vertices, Finset.mem_insert] at hyE hyF
    have hyEdgeE : y ∈ e.1.1.1.toFinset := by
      rcases hyE with hyHost | hyEdge
      · exact (hyx (hyHost.trans hxHostE.symm)).elim
      · exact hyEdge
    have hyEdgeF : y ∈ f.1.1.1.toFinset := by
      rcases hyF with hyHost | hyEdge
      · exact (hyx (hyHost.trans hxHostF.symm)).elim
      · exact hyEdge
    have hmeet : EdgesMeet e.1.1 f.1.1 :=
      ⟨y, Sym2.mem_toFinset.mp hyEdgeE,
        Sym2.mem_toFinset.mp hyEdgeF⟩
    have hassigned : assignedColor C S e.1 = assignedColor C S f.1 := by
      apply assign.injective
      apply Subtype.ext
      exact hhost
    have hcolor : C.color e.1.1 = C.color f.1.1 :=
      congrArg Subtype.val hassigned
    have hresource : e.1.1 = f.1.1 := by
      by_contra hne
      exact C.proper hne hmeet hcolor
    apply Subtype.ext
    apply Subtype.ext
    exact hresource
  · have hAOutside : ∀ z ∈ r.1.toFinset, z ∈ outsideVertices P := by
      intro z hz
      by_contra hzOut
      exact hroot ⟨z, hz, by simpa using hzOut⟩
    have hsubE : r.1.toFinset ⊆ e.1.1.1.toFinset := by
      intro z hz
      have hzTri := her hz
      simp only [vertices, Finset.mem_insert] at hzTri
      rcases hzTri with hzHost | hzEdge
      · have hzP : z ∈ P := hzHost ▸ host_mem_root O C S assign e
        exact ((mem_outsideVertices.mp (hAOutside z hz)) hzP).elim
      · exact hzEdge
    have hsubF : r.1.toFinset ⊆ f.1.1.1.toFinset := by
      intro z hz
      have hzTri := hfr hz
      simp only [vertices, Finset.mem_insert] at hzTri
      rcases hzTri with hzHost | hzEdge
      · have hzP : z ∈ P := hzHost ▸ host_mem_root O C S assign f
        exact ((mem_outsideVertices.mp (hAOutside z hz)) hzP).elim
      · exact hzEdge
    have hrCard : r.1.toFinset.card = 2 := by
      let rf : ↑G.edgeFinset := ⟨r.1, G.mem_edgeFinset.mpr r.2⟩
      exact G.card_toFinset_mem_edgeFinset rf
    have hEqE : r.1.toFinset = e.1.1.1.toFinset :=
      Finset.eq_of_subset_of_card_le hsubE (by
        rw [resource_toFinset_card, hrCard])
    have hEqF : r.1.toFinset = f.1.1.1.toFinset :=
      Finset.eq_of_subset_of_card_le hsubF (by
        rw [resource_toFinset_card, hrCard])
    have hresource : e.1.1 = f.1.1 := by
      apply Subtype.ext
      apply Sym2.ext
      intro z
      rw [← Sym2.mem_toFinset, ← Sym2.mem_toFinset,
        ← hEqE, ← hEqF]
    apply Subtype.ext
    apply Subtype.ext
    exact hresource

/-- The retained outside edges form an edge-disjoint triangle packing. -/
noncomputable def packing {G : SimpleGraph V} [DecidableRel G.Adj]
    {P : Finset V} (O : RootedPEO.Order G P)
    (C : ProperEdgeColoring (outsideGraph G P) Color)
    (S : Finset Color) (assign : ↑S ≃ ↑P) :
    TrianglePacking.Packing G := by
  classical
  let emb : ↑(retainedAssignedEdges O C S assign) ↪ CliqueOfOrder G 3 :=
    ⟨triangle O C S assign, triangle_injective O C S assign⟩
  refine
    { triangles := Finset.univ.map emb
      exclusive := ?_ }
  intro T U hT hU r hTr hUr
  obtain ⟨e, _he, rfl⟩ := Finset.mem_map.mp hT
  obtain ⟨f, _hf, rfl⟩ := Finset.mem_map.mp hU
  exact congrArg (triangle O C S assign)
    (eq_of_shared_edge O C S assign e f r hTr hUr)

theorem card_packing {G : SimpleGraph V} [DecidableRel G.Adj]
    {P : Finset V} (O : RootedPEO.Order G P)
    (C : ProperEdgeColoring (outsideGraph G P) Color)
    (S : Finset Color) (assign : ↑S ≃ ↑P) :
    (packing O C S assign).triangles.card =
      (retainedAssignedEdges O C S assign).card := by
  classical
  rw [packing, Finset.card_map, Finset.card_univ, Fintype.card_coe]

/-- Retained edges assigned to a specified root vertex. -/
noncomputable def hostedEdgesAt {G : SimpleGraph V} [DecidableRel G.Adj]
    {P : Finset V} (O : RootedPEO.Order G P)
    (C : ProperEdgeColoring (outsideGraph G P) Color)
    (S : Finset Color) (assign : ↑S ≃ ↑P) (x : V) :
    Finset ↑(retainedAssignedEdges O C S assign) := by
  classical
  exact Finset.univ.filter fun e ↦ assignedHost C S assign e.1 = x

/-- Outside vertices whose spokes at `x` are consumed by hosted outside-edge
triangles. -/
noncomputable def usedOutsideVertices {G : SimpleGraph V}
    [DecidableRel G.Adj] {P : Finset V}
    (O : RootedPEO.Order G P)
    (C : ProperEdgeColoring (outsideGraph G P) Color)
    (S : Finset Color) (assign : ↑S ≃ ↑P) (x : V) : Finset V := by
  classical
  exact (hostedEdgesAt O C S assign x).biUnion fun e ↦ e.1.1.1.toFinset

/-- At a root vertex, all hosted edges lie in its assigned colour class. -/
theorem card_hostedEdgesAt_le_colorClass {G : SimpleGraph V}
    [DecidableRel G.Adj] {P : Finset V}
    (O : RootedPEO.Order G P)
    (C : ProperEdgeColoring (outsideGraph G P) Color)
    (S : Finset Color) (assign : ↑S ≃ ↑P)
    {x : V} (hx : x ∈ P) :
    (hostedEdgesAt O C S assign x).card ≤
      (colorClass C ((assign.symm ⟨x, hx⟩ : ↑S) : Color)).card := by
  classical
  apply Finset.card_le_card_of_injOn
    (fun e : ↑(retainedAssignedEdges O C S assign) ↦ e.1.1)
  · intro e he
    have heHost : assignedHost C S assign e.1 = x :=
      (Finset.mem_filter.mp he).2
    apply (mem_colorClass C).mpr
    have hassign : assign (assignedColor C S e.1) = ⟨x, hx⟩ := by
      apply Subtype.ext
      exact heHost
    have hcolorSubtype : assignedColor C S e.1 = assign.symm ⟨x, hx⟩ := by
      apply assign.injective
      simpa using hassign
    exact congrArg Subtype.val hcolorSubtype
  · intro e he f hf hef
    apply Subtype.ext
    apply Subtype.ext
    exact hef

/-- If every colour class has at most `t` edges, each root vertex consumes at
most `2t` outside spokes. -/
theorem card_usedOutsideVertices_le {G : SimpleGraph V}
    [DecidableRel G.Adj] {P : Finset V}
    (O : RootedPEO.Order G P)
    (C : BoundedColoring (outsideGraph G P) Color t)
    (S : Finset Color) (assign : ↑S ≃ ↑P)
    {x : V} (hx : x ∈ P) :
    (usedOutsideVertices O C.toProper S assign x).card ≤ 2 * t := by
  classical
  calc
    (usedOutsideVertices O C.toProper S assign x).card ≤
        (hostedEdgesAt O C.toProper S assign x).card * 2 := by
      exact Finset.card_biUnion_le_card_mul
        (hostedEdgesAt O C.toProper S assign x)
        (fun e ↦ e.1.1.1.toFinset) 2 (fun e _he ↦ by
          exact (resource_toFinset_card e.1.1).le)
    _ ≤ t * 2 := Nat.mul_le_mul_right 2
      ((card_hostedEdgesAt_le_colorClass O C.toProper S assign hx).trans
        (C.class_card_le _))
    _ = 2 * t := Nat.mul_comm _ _

end HostedTriangles
end Erdos81
